StaffMode-Enter-Broadcast: '&7[Staff] &aPlayer has entered Staff Mode.'
StaffMode-Leave-Broadcast: '&7[Staff] &cPlayer has exited Staff Mode.'
StaffMode-Enter: '&7[Staff] &aYou have entered Staff Mode.'
StaffMode-Leave: '&7[Staff] &cYou have exited Staff Mode.'
Vanish-Enter: '&7[Staff] &aYou have entered Vanish Mode.'
Vanish-Leave: '&7[Staff] &cYou have exited Vanish Mode.'
NoClip-Enter: '&7[Staff] &aYou have entered NoClip Mode.'
NoClip-Leave: '&7[Staff] &cYou have exited NoClip Mode.'