StaffMode-Enter-Broadcast: '&7[Staff] &a%Player% has entered Staff Mode.'
StaffMode-Leave-Broadcast: '&7[Staff] &c%Player% has exited Staff Mode.'
StaffMode-Enter: '&7[Staff] &aYou have entered Staff Mode.'
StaffMode-Leave: '&7[Staff] &cYou have exited Staff Mode.'
Vanish-Enter: '&7[Staff] &aYou have entered Vanish Mode.'
Vanish-Leave: '&7[Staff] &cYou have exited Vanish Mode.'
NoClip-Enter: '&7[Staff] &aYou have entered NoClip Mode.'
NoClip-Leave: '&7[Staff] &cYou have exited NoClip Mode.'
PlayerNotFound: '&7[Staff] &c%Player% not found!'
Freeze:
  Freeze-Message: '&7[Staff] &a%Player% is now frozen.'
  Unfreeze-Message: '&7[Staff] &c%Player% is not frozen anymore.'
  Hologram: '%Player% is now frozen!'
  CommandExecutedOnDisconnect: 'list'
  MessageSentToPlayer: 'You are frozen'
Follow-Start: '&7[Staff] &aYou started following %Player%.'
Follow-Stop: '&7[Staff] &cYou stopped following %Player%.'