Staffpermission: 'staff'
PlayerNotFound: '&7[Staff] &c%Player% not found!'
StaffMode:
  Enter-Broadcast: '&7[Staff] &a%Player% has entered Staff Mode.'
  Leave-Broadcast: '&7[Staff] &c%Player% has exited Staff Mode.'
  Enter: '&7[Staff] &aYou have entered Staff Mode.'
  Leave: '&7[Staff] &cYou have exited Staff Mode.'
Vanish:
  Enter: '&7[Staff] &aYou have entered Vanish Mode.'
  Leave: '&7[Staff] &cYou have exited Vanish Mode.'
NoClip:
  Enter: '&7[Staff] &aYou have entered NoClip Mode.'
  Leave: '&7[Staff] &cYou have exited NoClip Mode.'
Freeze:
  Freeze-Message: '&7[Staff] &a%Player% is now frozen.'
  Unfreeze-Message: '&7[Staff] &c%Player% is not frozen anymore.'
  Hologram: '%Player% is now frozen!'
  CommandExecutedOnDisconnect: 'list'
  MessageSentToPlayer: 'You are frozen'
Follow:
  Start: '&7[Staff] &aYou started following %Player%.'
  Stop: '&7[Staff] &cYou stopped following %Player%.'
HotBar:
  1:
    Module: 'Vanish Mode'
    Type: 373
    NameOn: '&7Vanish Mode &a&lON'
    NameOff: '&7Vanish Mode &c&lOFF'
    Lore: []
  2:
    Module: 'No Clip'
    Type: 288
    NameOn: '&7NoClip Mode &a&lON'
    NameOff: '&7NoClip Mode &c&lOFF'
    Lore: []
  3:
    Module: 'Player Options'
    Type: '397:3'
    NameOn: '&aFollowing %Player%'
    NameOff: '&cNot following a player'
    Lore: []
  4:
    Module: 'TP To Miners'
    Type: 1
    NameOn: '&7Open Miners GUI'
    NameOff: '&7Miners GUI Opened'
    Lore: []
  5:
    Module: 'Staff Online'
    Type: 264
    NameOn: '&7Open Staff Online GUI'
    NameOff: '&7Staff GUI opened'
    Lore: []
PlayerOptionsGUI:
  0:
    Type: 345
    Name: '&7 CPS test'
    Lore:
      - 'Test CPS'
    Command: 'cps %Player% 10'
  1:
    Type: 79
    Name: '&7 Freeze Player'
    Lore: []
    Command: 'freeze %Player%'
  2:
    Type: 326
    Name: '&7 Unfreeze Player'
    Lore: []
    Command: 'unfreeze %Player%'
  3:
    Type: 329
    Name: '&7 Unfollow Player'
    Lore: []
    Command: 'follow %Player%'
CPS-Start: '&7[Staff] &aYou started a cps check for %Player%.'
Teleport-Menu:
  Y-Number: 25
  Auto-Follow: true
StaffOnline:
  Title: '&6TestTitle'
  Lore:
    - '%staffmodeplusplus_isVanished%'
    - '%staffmodeplusplus_amountUnderground%'